name: Runreal
description: Download runreal and makes available to environment
author: https://github.com/chainkemists
requirements: []
configuration:
  properties:
    version:
      type: string
      default: latest
  additionalProperties: true